apiVersion: v1
kind: Service
metadata:
  name: conv-app-port-srv
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 80
      nodePort: 31100
  selector:
    components: conv-app-front
