apiVersion: v1
kind: Secret
metadata:
  name: conv-secrets
type: Opaque
data:
  SEED_USERNAME: Z3Vlc3Q=
  SEED_USER_PASSWORD: Z3Vlc3Q=
  AMQP_EXCHANGE: Y29udi10ZXN0
  AMQP_USER: Z3Vlc3Q=
  AMQP_PASSWORD: Z3Vlc3Q=
  AMQP_HOSTNAME: cm1xLWNsdXN0ZXItaXA=
  AMQP_QUEUE: Y29udmVydGVy

