apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: conv-service-backend
  template:
    metadata:
      labels:
        components: conv-service-backend
    spec:
      containers:
      - name: conv-service
        image: antonlarichev/conv-service:1.0
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        resources:
          limits:
            memory: "500Mi"
            cpu: "300m"
        env:
          - name: AMQP_EXCHANGE
            valueFrom:
              secretKeyRef:
                name: conv-secrets
                key: AMQP_EXCHANGE
          - name: AMQP_USER
            valueFrom:
              secretKeyRef:
                name: conv-secrets
                key: AMQP_USER
          - name: AMQP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: conv-secrets
                key: AMQP_PASSWORD
          - name: AMQP_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: conv-secrets
                key: AMQP_HOSTNAME
          - name: AMQP_QUEUE
            valueFrom:
              secretKeyRef:
                name: conv-secrets
                key: AMQP_QUEUE
