apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}-secrets
type: Opaque
data:
  SEED_USERNAME: {{ .Values.seed_envs.seed_username | b64enc }}
  SEED_USER_PASSWORD: {{ .Values.seed_envs.seed_user_password: | b64enc }}
  AMQP_EXCHANGE: {{ .Values.amqp_envs.amqp_exchange | b64enc }}
  AMQP_USER: {{ .Values.amqp_envs.amqp_user | b64enc }}
  AMQP_PASSWORD: {{ .Values.amqp_envs.amqp_pw | b64enc }}
  AMQP_HOSTNAME: {{ .Values.amqp_envs.amqp_hostname | b64enc  }}
  AMQP_QUEUE: {{ .Values.amqp_envs.amqp_queue | b64enc }}

