apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deployment
spec:
  replicas: {{ .Values.app.relicas }}
  selector:
    matchLabels:
      components: {{ .Values.app.components }}
  template:
    metadata:
      labels:
        components: {{ .Values.app.components }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: "{{ .Values.app.image }}:{{ .Values.app.version }}"
        imagePullPolicy: Always
        ports:
          - containerPort: {{ .Values.app.port }}
        env:
          - name: {{ .Values.app.env_name }}
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.app.name }}-configmap
                key: {{ .Values.app.env_name }}
        resources:
          limits: {{ .Values.app.limits  | toYaml | nindent 12 }}

