apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: {{ .Values.service.components }}
  template:
    metadata:
      labels:
        components: {{ .Values.service.components }}
    spec:
      containers:
      - name: {{ .Values.service.name }}
        image: "{{ .Values.service.image }}:{{ .Values.service.version }}"
        imagePullPolicy: Always
        ports:
          - containerPort: {{ .Values.service.port }}
        resources:
          limits: {{ .Values.service.limits | toYaml | nindent 14 }}
        env:
          - name: AMQP_EXCHANGE
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.name }}-secrets
                key: AMQP_EXCHANGE
          - name: AMQP_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.name }}-secrets
                key: AMQP_USER
          - name: AMQP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.name }}-secrets
                key: AMQP_PASSWORD
          - name: AMQP_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.name }}-secrets
                key: AMQP_HOSTNAME
          - name: AMQP_QUEUE
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.name }}-secrets
                key: AMQP_QUEUE
