apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.rmq.name }}-cluster-ip"
spec:
  type: ClusterIP
  selector:
    components: {{ .Values.rmq.components }}
  ports:
  - port: {{ .Values.rmq.port }}
    protocol: TCP
